import Link from 'next/link';
import './catalog.css';
const standards=[['01','Carefully Selected','Quality-first sourcing for a better seafood experience.'],['02','Properly Handled','Clean, careful handling from stock-in to customer handoff.'],['03','Freshly Delivered','Simple ordering built around freshness and convenience.']];

const catalog=[
{name:'Yellowfin Tuna',type:'Ocean favorite',price:'₱520',size:'1 kg cuts',stock:'In stock',icon:'🐟',tone:'tuna',description:'Lean, meaty and clean-tasting—excellent for grilling, searing or kinilaw.',origin:'Philippine waters',preparation:'Steaks, loin cuts or whole',storage:'Keep chilled at 0–4°C; cook within 2 days'},
{name:'Atlantic Salmon',type:'Premium fillet',price:'₱760',size:'500 g / 1 kg',stock:'In stock',icon:'🍣',tone:'salmon',description:'Rich, buttery fillets suited for pan-searing, baking, grilling and sashimi-style dishes.',origin:'Imported, responsibly sourced',preparation:'Skin-on fillet or portion cuts',storage:'Keep chilled at 0–4°C; cook within 2 days'},
{name:'White Shrimp',type:'Kitchen essential',price:'₱430',size:'500 g / 1 kg',stock:'In stock',icon:'🦐',tone:'shrimp',description:'Sweet, firm shrimp for sinigang, buttered shrimp, pasta and everyday meals.',origin:'Locally sourced',preparation:'Whole, headless or peeled',storage:'Keep chilled; cook within 24 hours'},
{name:'Fresh Squid',type:'Cleaned whole',price:'₱360',size:'500 g / 1 kg',stock:'Limited',icon:'🦑',tone:'squid',description:'Tender squid selected for grilling, adobo, calamari and stuffed preparations.',origin:'Philippine waters',preparation:'Whole or cleaned and sliced',storage:'Keep chilled; cook within 24 hours'},
{name:'Blue Swimming Crab',type:'Wild caught',price:'₱480',size:'1 kg pack',stock:'In stock',icon:'🦀',tone:'crab',description:'Naturally sweet crab ideal for steaming, ginataan, soups and special gatherings.',origin:'Wild caught locally',preparation:'Whole, cleaned on request',storage:'Keep chilled and cook the same day'},
{name:'Premium Bangus',type:'Butterflied option',price:'₱290',size:'700–900 g',stock:'In stock',icon:'🐠',tone:'bangus',description:'Fresh milkfish with delicate flavor for frying, grilling, paksiw or rellenong bangus.',origin:'Philippine aquaculture',preparation:'Whole, cleaned or butterflied',storage:'Keep chilled at 0–4°C; cook within 2 days'}];
export default function Home(){return <main>
<header><div className="wrap nav"><Link href="#top" className="brand"><img src="/elisha-prime-logo-v2.png" alt="Elisha Prime Seafoods" width="96" height="64"/></Link><nav><a href="#fresh">Fresh Today</a><a href="#shop">Shop</a><a href="#recipes">Recipes</a><a href="#bulk">Bulk Orders</a><a href="#about">About</a></nav><a className="btn small" href="#order">Order Now</a></div></header>
<section id="top" className="hero"><div className="wrap heroGrid"><div><p className="eyebrow">ELISHA PRIME SEAFOODS</p><h1>Premium from the sea.<br/><span>Fresh to your table.</span></h1><p className="lead">Carefully selected seafood for families, food businesses and anyone who values freshness without compromise.</p><div className="actions"><a className="btn" href="#shop">Shop Fresh Seafood</a><a className="link" href="#fresh">View today's catch ↗</a></div></div><div className="heroLogo"><img src="/elisha-prime-logo-v2.png" alt="Elisha Prime Seafoods logo" width="600" height="400"/></div></div></section>
<section className="ticker"><div className="wrap">FRESH <b>•</b> PREMIUM <b>•</b> CAREFULLY HANDLED <b>•</b> DELIVERED</div></section>
<section id="fresh" className="section light"><div className="wrap"><p className="eyebrow dark">TODAY'S FRESH CATCH</p><h2>Fresh stock, made simple.</h2><div className="fresh"><div className="fish">POMPANO</div><div><p className="status">● FRESH STOCK AVAILABLE</p><h3>Premium Pompano</h3><p>Firm, clean-tasting and versatile—ideal for frying, grilling, steaming and family meals.</p><div className="stats"><div><small>PRICE</small><strong>₱380 <em>/ kg</em></strong></div><div><small>AVAILABLE</small><strong>18.5 <em>kg</em></strong></div></div><a className="btn navyBtn" href="#order">Order Pompano</a></div></div></div></section>
<section id="shop" className="section darkSec catalogSection"><div className="wrap"><div className="catalogIntro"><div><p className="eyebrow">SHOP THE SELECTION</p><h2>Premium seafood,<br/>ready for your table.</h2></div><p>Choose from our everyday favorites. Prices and availability shown here are samples and can be updated with your final inventory.</p></div><div className="catalogGrid">{catalog.map(item=><article className="productCard" key={item.name}><div className={`productVisual ${item.tone}`}><span aria-hidden="true">{item.icon}</span><small>{item.type}</small></div><div className="productInfo"><div className="productTop"><p className={`stock ${item.stock==='Limited'?'limited':''}`}>● {item.stock}</p><small>{item.size}</small></div><h3>{item.name}</h3><div className="productBottom"><strong>{item.price}<small>/kg</small></strong><a href="#order" aria-label={`Order ${item.name}`}>Order <span>↗</span></a></div><details className="productDetails"><summary>Product details <span>+</span></summary><div><p>{item.description}</p><dl><div><dt>Source</dt><dd>{item.origin}</dd></div><div><dt>Preparation</dt><dd>{item.preparation}</dd></div><div><dt>Storage</dt><dd>{item.storage}</dd></div></dl></div></details></div></article>)}</div><div className="catalogNote"><span>Need something else?</span><p>Ask us about seasonal catch, custom cuts, cleaned seafood, and family bundles.</p><a className="outline compact" href="#order">Request a product</a></div></div></section>
<section id="about" className="section light"><div className="wrap"><p className="eyebrow dark center">THE ELISHA PRIME STANDARD</p><h2 className="center">The logo says seafood.<br/>The experience says premium.</h2><div className="standards">{standards.map(s=><article key={s[0]}><span>{s[0]}</span><h3>{s[1]}</h3><p>{s[2]}</p></article>)}</div></div></section>
<section id="recipes" className="section pearl"><div className="wrap two"><div><p className="eyebrow dark">RECIPES & INSPIRATION</p><h2>From fresh catch<br/>to memorable meals.</h2><p>Recipe pages can lead customers directly back to the seafood used.</p></div><div className="recipes"><div>01 <strong>Crispy Fried Pompano</strong></div><div>02 <strong>Steamed Pompano</strong></div><div>03 <strong>Sweet & Sour Pompano</strong></div></div></div></section>
<section id="bulk" className="section darkSec"><div className="wrap bulk"><div><p className="eyebrow">FOR RESTAURANTS & BUSINESSES</p><h2>Need seafood in volume?</h2><p>Recurring supply, bulk requests and business pricing can use a dedicated flow.</p></div><a className="btn" href="#order">Request a quote</a></div></section>
<section id="order" className="section light"><div className="wrap two"><div><p className="eyebrow dark">ORDER FRESH TODAY</p><h2>Your seafood order,<br/>without the friction.</h2><p>This V1 interface is ready for the Supabase order and inventory layer.</p></div><form><label>Name<input placeholder="Your full name"/></label><label>Mobile number<input placeholder="09XX XXX XXXX"/></label><div className="row"><label>Product<select><option>Premium Pompano</option>{catalog.map(item=><option key={item.name}>{item.name}</option>)}</select></label><label>Weight<input placeholder="e.g. 2.5 kg"/></label></div><label>Delivery / pickup details<textarea rows={3} placeholder="Address, landmark or pickup arrangement"/></label><button type="button" className="btn navyBtn">Submit Order Request</button><small>Demo interface — database submission comes next.</small></form></div></section>
<footer><div className="wrap footer"><img src="/elisha-prime-logo-v2.png" alt="Elisha Prime Seafoods" width="117" height="78"/><div><strong>ELISHA PRIME SEAFOODS</strong><p>Fresh. Premium. Delivered.</p></div><Link href="/admin">Admin Dashboard →</Link></div></footer>
</main>}
