import Image from 'next/image';
import Link from 'next/link';
const standards=[['01','Carefully Selected','Quality-first sourcing for a better seafood experience.'],['02','Properly Handled','Clean, careful handling from stock-in to customer handoff.'],['03','Freshly Delivered','Simple ordering built around freshness and convenience.']];
export default function Home(){return <main>
<header><div className="wrap nav"><Link href="#top" className="brand"><Image src="/elisha-logo.jpg" alt="Elisha Prime Seafoods" width={64} height={64}/></Link><nav><a href="#fresh">Fresh Today</a><a href="#shop">Shop</a><a href="#recipes">Recipes</a><a href="#bulk">Bulk Orders</a><a href="#about">About</a></nav><a className="btn small" href="#order">Order Now</a></div></header>
<section id="top" className="hero"><div className="wrap heroGrid"><div><p className="eyebrow">ELISHA PRIME SEAFOODS</p><h1>Premium from the sea.<br/><span>Fresh to your table.</span></h1><p className="lead">Carefully selected seafood for families, food businesses and anyone who values freshness without compromise.</p><div className="actions"><a className="btn" href="#shop">Shop Fresh Seafood</a><a className="link" href="#fresh">View today's catch ↗</a></div></div><div className="heroLogo"><Image src="/elisha-logo.jpg" alt="Elisha Prime Seafoods logo" width={500} height={500} priority/></div></div></section>
<section className="ticker"><div className="wrap">FRESH <b>•</b> PREMIUM <b>•</b> CAREFULLY HANDLED <b>•</b> DELIVERED</div></section>
<section id="fresh" className="section light"><div className="wrap"><p className="eyebrow dark">TODAY'S FRESH CATCH</p><h2>Fresh stock, made simple.</h2><div className="fresh"><div className="fish">POMPANO</div><div><p className="status">● FRESH STOCK AVAILABLE</p><h3>Premium Pompano</h3><p>Firm, clean-tasting and versatile—ideal for frying, grilling, steaming and family meals.</p><div className="stats"><div><small>PRICE</small><strong>₱380 <em>/ kg</em></strong></div><div><small>AVAILABLE</small><strong>18.5 <em>kg</em></strong></div></div><a className="btn navyBtn" href="#order">Order Pompano</a></div></div></div></section>
<section id="shop" className="section darkSec"><div className="wrap"><p className="eyebrow">OUR SEAFOOD</p><h2>Start with one product.<br/>Build a trusted seafood house.</h2><div className="products"><article><p className="micro">SIGNATURE CATCH</p><h3>Premium Pompano</h3><strong className="price">₱380<small>/kg</small></strong><p>Fresh stock for everyday family meals, celebrations and food businesses.</p><a className="outline" href="#order">Add to order</a></article><article><p className="micro">COMING NEXT</p><h3>More premium seafood.</h3><p>Shrimp, squid, crabs, shellfish, bundles and seasonal catches can be added as the store grows.</p></article></div></div></section>
<section id="about" className="section light"><div className="wrap"><p className="eyebrow dark center">THE ELISHA PRIME STANDARD</p><h2 className="center">The logo says seafood.<br/>The experience says premium.</h2><div className="standards">{standards.map(s=><article key={s[0]}><span>{s[0]}</span><h3>{s[1]}</h3><p>{s[2]}</p></article>)}</div></div></section>
<section id="recipes" className="section pearl"><div className="wrap two"><div><p className="eyebrow dark">RECIPES & INSPIRATION</p><h2>From fresh catch<br/>to memorable meals.</h2><p>Recipe pages can lead customers directly back to the seafood used.</p></div><div className="recipes"><div>01 <strong>Crispy Fried Pompano</strong></div><div>02 <strong>Steamed Pompano</strong></div><div>03 <strong>Sweet & Sour Pompano</strong></div></div></div></section>
<section id="bulk" className="section darkSec"><div className="wrap bulk"><div><p className="eyebrow">FOR RESTAURANTS & BUSINESSES</p><h2>Need seafood in volume?</h2><p>Recurring supply, bulk requests and business pricing can use a dedicated flow.</p></div><a className="btn" href="#order">Request a quote</a></div></section>
<section id="order" className="section light"><div className="wrap two"><div><p className="eyebrow dark">ORDER FRESH TODAY</p><h2>Your seafood order,<br/>without the friction.</h2><p>This V1 interface is ready for the Supabase order and inventory layer.</p></div><form><label>Name<input placeholder="Your full name"/></label><label>Mobile number<input placeholder="09XX XXX XXXX"/></label><div className="row"><label>Product<select><option>Premium Pompano</option></select></label><label>Weight<input placeholder="e.g. 2.5 kg"/></label></div><label>Delivery / pickup details<textarea rows={3} placeholder="Address, landmark or pickup arrangement"/></label><button type="button" className="btn navyBtn">Submit Order Request</button><small>Demo interface — database submission comes next.</small></form></div></section>
<footer><div className="wrap footer"><Image src="/elisha-logo.jpg" alt="Elisha Prime Seafoods" width={78} height={78}/><div><strong>ELISHA PRIME SEAFOODS</strong><p>Fresh. Premium. Delivered.</p></div><Link href="/admin">Admin Dashboard →</Link></div></footer>
</main>}